---
title: "data import"
output: github_document
---
```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

##Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv(file = "./data/FAS_litters.csv")
litters_df = janitor:: clean_names(litters_df)
```
## Take a look at the data
Printing in the console.
```{r}
litters_df
```

```{r}
tail(litters_df)
```
```{r}
skimr::skim(litters_df)
```


##Option to read_csv

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

check out `?read_csv()` for more information.

#other file formats 
Read in Excel File 

```{r}
mlb11_df = read_excel("./data/mlb11.xlsx",range = "A1:F7" )
mlb11_df
```

Read in a SAS file.

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_data = janitor::clean_names(pulse_df)
```

##comparison with Base R

what about `read.csv`...?
```{r}
litters_base = read.csv(file = "./data/FAS_litters.csv")
litters_reader = read_csv(file = "./data/FAS_litters.csv")
litters_base
litters_reader
```

