---
title: "Data Manipulation"
output: github_document
---
```{r setup}
library(tidyverse)

```

##Load in the FAS litters Data
```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

##`select`

Choose some columns and not others.
```{r}
select(litters_df,group,gd0_weight)
```
```{r}
select(litters_df,group,gd0_weight:gd_of_birth)   #range of column

```

```{r}
select(litters_df,-litter_number) #get ride of -
```

renaming columns 

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```


```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df,litter_number,everything()) #star with litter_number
```

```{r}
relocate(litters_df,litter_number) #litter_number at the beginning 
```


##`filter`    
it is about row 

```{r}
filter(litters_df,gd0_weight < 22)
```

```{r}
filter(litters_df,gd0_weight >= 22)
```

```{r}
filter(litters_df,gd_of_birth == 20) #== test for equality
```

```{r}
filter(litters_df,gd_of_birth != 20)  #no equal
```

```{r}
filter(litters_df, gd0_weight >= 22,gd_of_birth == 20) #!()
```


```{r}
filter(litters_df,group == "Con7")
```

```{r}
filter(litters_df, group == "Mod8")
```

either Con7 or Mod8
```{r}
filter(litters_df, group %in% c("Mod8","Con7") )
```

##`mutate`
modify existing or create new variable

```{r}
mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```


##`arrange`

```{r}
arrange(litters_df,pups_born_alive)   #arrange by numberable order 
```




